name: Lynis Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday

jobs:
  security-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for Firebase
      issues: write    # Added for issue creation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > "${HOME}/firebase_credentials.json"

      - name: Authenticate Firebase
        run: |
          firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"
          firebase use --add --project flutter-firebase-auth-b4967
          export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/firebase_credentials.json"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies and build Docker image
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib numpy
          docker build -t lynis-audit .

      - name: Simulate security risk
        run: ./simulate_risk.sh

      - name: Setup Firebase CLI (official)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_CREDENTIALS }}'
          channelId: live
          projectId: flutter-firebase-auth-b4967

      - name: Run Lynis audit
        run: |
          docker run --rm --cap-add=SYS_ADMIN --cap-add=AUDIT_CONTROL -v /tmp:/tmp lynis-audit > lynis-result.txt
          docker run --rm lynis-audit lynis --version

      - name: Analyze results and run audit
        run: |
          python3 analyze_lynis.py
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          docker run --rm \
            --cap-add=SYS_ADMIN \
            --cap-add=AUDIT_CONTROL \
            -v "$(pwd)/logs:/audit/logs" \
            lynis-audit

      - name: Upload results to Firebase Storage
        if: always()
        run: |
          # Create timestamp for unique filenames
          TIMESTAMP=$(date +%F-%H-%M-%S)
          
          # Upload files using correct Firebase Storage syntax
          firebase storage:upload lynis-result.txt "lynis-results/${TIMESTAMP}-lynis-result.txt"
          firebase storage:upload lynis_summary.png "lynis-results/${TIMESTAMP}-lynis-summary.png"
          
          # Upload log files
          for file in logs/*; do
            if [ -f "$file" ]; then
              firebase storage:upload "$file" "lynis-results/$(basename "$file")"
            fi
          done

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Lynis Audit Failed',
                body: 'The automated security audit failed. Please check the workflow run for details.'
              });
            } catch (error) {
              console.error('Failed to create issue:', error.message);
            }