name: Lynis Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Chạy mỗi Chủ nhật

jobs:
  security-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Cần thiết cho Firebase

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy

    # Thay thế Firebase action cũ bằng action chính thức
    - name: Setup Firebase CLI
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_CREDENTIALS }}'
        channelId: live
        projectId: flutter-firebase-auth-b4967

    - name: Build and test Docker image
      run: |
        docker build -t lynis-audit .
        docker run --rm lynis-audit lynis --version

    - name: Run security audit
      run: |
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        docker run --rm \
          --cap-add=SYS_ADMIN \
          --cap-add=AUDIT_CONTROL \
          -v "$(pwd)/logs:/audit/logs" \
          lynis-audit

    - name: Upload results to Firebase Storage
      if: always()
      run: |
        # Cài đặt Firebase CLI
        npm install -g firebase-tools
        
        # Login vào Firebase
        firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"
        
        # Upload files
        for file in logs/*; do
          if [ -f "$file" ]; then
            firebase storage:upload "$file" \
              --bucket flutter-firebase-auth-b4967.appspot.com \
              --path "/lynis-results/$(basename "$file")"
          fi
        done

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Lynis Audit Failed',
            body: 'The automated security audit failed. Please check the workflow run for details.'
          })